language: node_js
node_js:
  - 16
branches:
  only:
    - main
    - container-cleaning
install:
  - npm install
  - npm exec -ws -- npm install
script:
  - npm run build
  - npm run test
  - npm run docs:prod
  - npm run test:coverage:coveralls
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
